apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-k8s-apiserver
  namespace: bank-of-anthos
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 172.18.0.5/32
      ports:
        - protocol: TCP
          port: 6443
