apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-k8s-apiserver
  namespace: bank-of-anthos
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
      ports:
        - protocol: TCP
          port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: patroni-primary
  namespace: bank-of-anthos
spec:
  selector:
    app: patroni
    role: master
  ports:
    - name: postgres
      port: 5432
